server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location = / {
        return 302 /battle-plan/;
    }

    location = /battle-plan/sw.js {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    location /battle-plan/ {
        try_files $uri $uri/ /battle-plan/index.html;
    }
}
